server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8001/springbootsecurity?serverTimezone=Asia/Seoul
    username: root
    password: toor
    
  security:
    user:
      name: test
      password: 1234   
    oauth2:      client:        registration:          google:
            client-id: 43889814256-38l534v8bf6qs0eba4o9njf23e0o961n.apps.googleusercontent.com
            client-secret: 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
            scope:            - email
            - profile
          facebook:
            client-id: 954183248511214
            client-secret: c9af41360382ce338761c54d8f7dd86d
            scope:            - email
            - public_profile
          naver:
            client-id: v6386Tz11IY0OYYCDePd
            client-secret: ELmqWj0i9m
            scope:            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 가지고 올때 response라는 key값으로 데이터를 전달해 준다.

mybatis:
  mapper-locations:
  - /mappers/*.xml



#레오가 작업한 내용








