server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8001/springbootsecurity?serverTimezone=Asia/Seoul
    username: root
    password: toor
    
  security:
    user:
      name: test
      password: 1234   
    oauth2:
      client:
        registration:
          google:
            client-id: 88304863044-e6gfjqg5o8hcgiphn1bdaf8akifgpid3.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 457678355779350
            client-secret: a131b40f97f79c39de600f59eb1bb0ca
            scope:
            - email
            - public_profile
          naver:
            client-id: Kmg89Wf3MyhfxAUwIO2n
            client-secret: L8E7LbhQZ1
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: http://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 전달할때 response key값으로 데이터를 전달함.
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamproject85123@gmail.com
    password: xlavmfhwprxm0
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
mybatis:
  mapper-locations:
  - /mappers/*.xml