server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8001/springbootsecurity?serverTimezone=Asia/Seoul
    username: root
    password: toor
    
  security:
    user:
      name: test
      password: 1234   
    oauth2:      client:        registration:          google:
            client-id: 43889814256-38l534v8bf6qs0eba4o9njf23e0o961n.apps.googleusercontent.com
            client-secret: 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
            scope:            - email
            - profile
          #facebook:
          #naver:

mybatis:
  mapper-locations:
  - /mappers/*.xml












